grafana:
    enabled: false
prometheus:
    enabled: true
    prometheusSpec:
        remoteWrite:
            - url: "https://prometheus-prod-22-prod-eu-west-3.grafana.net/api/prom/push"
              basicAuth:
                  username:
                      name: kubepromsecret
                      key: username
                  password:
                      name: kubepromsecret
                      key: password
        replicaExternalLabelName: "__replica__"
        externalLabels:
            cluster: "discard-prom-cluster"
