---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: user-service-monitor
    labels:
        release: prometheus
        app: prometheus
        prometheus: kube-prometheus
spec:
    # jobLabel: job
    endpoints:
        - port: api
          interval: 10s
          path: /api/v1/user/metrics
    selector:
        matchLabels:
            app: user-api
    namespaceSelector:
        matchNames:
            - default
